### ISSUE TITLE
Slow scrolling on mobiles

### ISSUE THREAD

**Issue by Johnnychaos** [vitch/jScrollPane#303]
jScrollPane works on mobile browsers, but not very quickly. Usually on mobiles when you make fast finger move then page scrolls fast, with jScrollPane is moves only by finger distance which is annoying on big scrolls.

Is there maybe a way to tweak it for mobile browsers? 
ps. tested on Chrome (android) and Safari (iOS).

Regards
Jan

**Comment by JonMcL** [comment]
I do not know about Android, but on iOS the problem is because of the way webkit treats DIVs with overflow:scroll. The problem isn’t unique to jScrollPane.

On iOS, you set the CSS property -webkit-overflow-scrolling:touch;

See https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-overflow-scrolling <https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-overflow-scrolling>

> On May 19, 2015, at 10:40 AM, Johnnychaos <notifications@github.com> wrote:
> 
> jScrollPane works on mobile browsers, but not very quickly. Usually on mobiles when you make fast finger move then page scrolls fast, with jScrollPane is moves only by finger distance which is annoying on big scrolls.
> 
> Is there maybe a way to tweak it for mobile browsers? 
> ps. tested on Chrome (android) and Safari (iOS).
> 
> Regards
> Jan
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/vitch/jScrollPane/issues/303>.
> 



Jon McLaughlin
System Werks
----------------------------------------------------------
phone: 			(888) 750-7997
fax:   			(646) 405-4882
email: 			jon@system-werks.com
AIM / iMessage:	jon@system-werks.com
-----------------------------------------------------------

**Comment by Johnnychaos** [comment]
Thank you. I've found that it stops working on iOS8:
http://stackoverflow.com/questions/26176288/webkit-overflow-scrolling-touch-breaks-in-apples-ios8
