### ISSUE TITLE
jsp-will-scroll-y event doesn't fire

### ISSUE THREAD

**Issue by saadshahd** [vitch/jScrollPane#326]
When replacing `jsp-scroll-y` by `jsp-will-scroll-y` the event doesn't fire.

I'm using bower to get the component got version `v2.0.22 - 2015-04-25` but the current src at the repo is different than the local of mine and both are the same version.

**Comment by joehany** [comment]
+1

**Comment by saadshahd** [comment]
@vitch ping!

**Comment by vitch** [comment]
Does it work with the latest source code from this repo? I'm trying to understand if the problem is with what is released to bower or if it is with the code in the repo.

If the problem is with the code in the repo then I'd happily accept a PR. `jsp-will-scroll-y` was a recent community contribution and I'm not familiar with the code. Unfortunately I also don't really have time to maintain this plugin any more...

**Comment by saadshahd** [comment]
Hi @vitch, 
Just create a tag-release for the new patch `v2.0.23`

**Comment by vitch** [comment]
Done :)

**Comment by joehany** [comment]
@vitch Thank you very much for your help.

**Comment by saadshahd** [comment]
@vitch Thanks a lot :heart:, I can help with maintaining the component!

**Comment by vitch** [comment]
Thanks @saadshahd :smile_cat: 

It would be great if you (or anyone else) would like to help maintain jScrollPane. A good first step would probably be to go through the issues and see which are genuine and reproducible in a simple test case and then see what fixes can be proposed as PRs.

Or checking through the open PRs for which ones can be applied without breaking existing code and use-cases. To be honest, the most urgent thing is probably a test suite. If I had a decent test suite then I could more easily merge PRs without worrying about unexpected side effects...
