### ISSUE TITLE
Performance : use transform instead of top

### ISSUE THREAD

**Issue by HugoHeneault** [vitch/jScrollPane#344]
Hi there, 

I have a scroll zone with complexe layout, and scrolling is not smooth. 

Maybe using css `transform` instead of top/left positioning would fix that?

I don't know what to change in the code, but I can help if necessary. 

Thanks!

**Comment by vitch** [comment]
I'm afraid this might be a pretty big change with far reaching consequences. 

Unfortunately I don't really have time to support this repository any more so I am unlikely to make the relevant changes. If someone wants to provide a PR then I'd be happy to accept it. Or even to transfer ownership of the project to someone who has time to maintain it.

Javascript (and browsers) have moved on a lot since this project was started and it might be better to make a clean start or look at alternative (and perhaps more modern) alternatives.

**Comment by KingSora** [comment]
In case you want to switch plugins, I've written my own scrollbar plugin which uses this feature on capable browsers. I've worked really hard on it and even if its new, please consider to give it a shot. https://github.com/KingSora/OverlayScrollbars

**Comment by illuusio** [comment]
If you like to make PR I can discuss about this or then you can go @KingSora way
