### ISSUE TITLE
archive project / search for maintainers

### ISSUE THREAD

**Issue by DanielRuf** [vitch/jScrollPane#353]
It seems there are many open issues and pull requests which can be solved.

Currently there are way too many custom scrollbar solutions on GitHub and no real collaboration between projects and everyone reinvents the same. Would be great to see a few great solutions instead of many with not enough support by the community.

**Comment by illuusio** [comment]
I can feel the problem. jScrollPane is rather popular and old project in sense of internet time. If you or someone else is having extra time then it would be nice to help out with PRs besides that this bug should be closed as it's common problem with projects made with volunteer power.

**Comment by DanielRuf** [comment]
Generally I thought about *real* collaboration between all these scrollbar implementations and joining forces instead of having more solutions which all do the same but have different features.

This all makes frontend dev and decisions harder for developers.

**Comment by vitch** [comment]
This is my fault as the original author and maintainer of `jScrollPane`.

Unfortunately, I have not had any need for `jScrollPane` for many years and neither have I had the time to maintain it. 

@illuusio has very kindly recently volunteered to look after the project and has been working through the backlog of issues / PRs triaging and closing them.

`jScrollPane` was first written back [at the end of 2006](http://2008.kelvinluck.com/2006/12/jscrollpane-cross-browser-custom-scrollbars/trackback/index.html) (and v2 [written in 2010](https://github.com/vitch/jScrollPane/commit/e25b81046e06d782d1f5295c0de4865aca92bff1)) - a long time ago in the days before ES6 and the modern javascript ecosystem! 

Javascript has come a long way since then! As have browsers - a lot of the code in `jScrollPane` is to work around problems in browsers that probably nobody uses any more. 

To be perfectly honest I'm not sure how useful `jScrollPane` is in this day and age - if I did have the need for a custom scroll bar solution I'd certainly research the current status quo before reaching for it.

That said, I'm happy for it to be available to anyone who finds it useful and while I don't personally have time to maintain it I'm more than happy for other people to step up to the plate.

**Comment by DanielRuf** [comment]
Well but then also the move to an org account would make be helpful to build a team which could maintain it better.

**Comment by vitch** [comment]
If a team comes forward I'm happy to create the org account and move it...

**Comment by illuusio** [comment]
jScrollPane is as useful at it was 💃 . jQuery ain't poster child of web anymore but as it's base rock for more than one websites in internet then project can justify itself. It's not newest and using all new features but what the heck it delivers all things that it promises for me.
In my opinion if this is turned to organization it should be done after PR cleanup (all mergable stuff in and after that everyone free to start with clean table) but that would be faster if the would be more hands. Now it comes slowly as I have time.
